[package]
name = "etherise"
version = "0.1.0"
authors = ["Shoaib Ahmed <sufialhussaini@gmail.com>"]
edition = "2018"


[dependencies]
clap = "2"
rlp = "0.4.5"
rustc-hex = "1.0.0"
ethereum-types = "0.9.2"
keccak-hash = "0.5.0"
serde_json = "1.0"
